name: qw2py310
channels:
  - pytorch
  - https://mirrors.tuna.tsinghua.edu.cn/anaconda/pkgs/main
  - nvidia
  - https://mirrors.tuna.tsinghua.edu.cn/anaconda/cloud/conda-forge
  - https://mirrors.tuna.tsinghua.edu.cn/anaconda/cloud/bioconda/
  - https://mirrors.tuna.tsinghua.edu.cn/anaconda/cloud/conda-forge/
  - https://mirrors.tuna.tsinghua.edu.cn/anaconda/pkgs/main/
  - https://mirrors.tuna.tsinghua.edu.cn/anaconda/pkgs/free/
  - defaults
dependencies:
  - _libgcc_mutex=0.1
  - _openmp_mutex=4.5
  - blas=2.16
  - bzip2=1.0.8
  - ca-certificates=2024.7.4
  - cuda-cudart=12.1.105
  - cuda-cupti=12.1.105
  - cuda-libraries=12.1.0
  - cuda-nvrtc=12.1.105
  - cuda-nvtx=12.1.105
  - cuda-opencl=12.5.39
  - cuda-runtime=12.1.0
  - cuda-version=12.5
  - filelock=3.15.4
  - gmp=6.3.0
  - gmpy2=2.1.5
  - intel-openmp=2022.0.1
  - jinja2=3.1.4
  - ld_impl_linux-64=2.40
  - libblas=3.8.0
  - libcblas=3.8.0
  - libcublas=12.1.0.26
  - libcufft=11.0.2.4
  - libcufile=1.10.0.4
  - libcurand=10.3.6.39
  - libcusolver=11.4.4.55
  - libcusparse=12.0.2.55
  - libffi=3.4.2
  - libgcc-ng=14.1.0
  - libgfortran-ng=7.5.0
  - libgfortran4=7.5.0
  - libgomp=14.1.0
  - liblapack=3.8.0
  - liblapacke=3.8.0
  - libnpp=12.0.2.50
  - libnsl=2.0.1
  - libnvjitlink=12.1.105
  - libnvjpeg=12.1.1.14
  - libsqlite=3.46.0
  - libstdcxx-ng=14.1.0
  - libuuid=2.38.1
  - libxcrypt=4.4.36
  - libzlib=1.3.1
  - llvm-openmp=15.0.7
  - markupsafe=2.1.5
  - mkl=2020.2
  - mpc=1.3.1
  - mpfr=4.2.1
  - mpmath=1.3.0
  - ncurses=6.5
  - networkx=3.3
  - openssl=3.3.1
  - pip=24.0
  - python=3.10.14
  - python_abi=3.10
  - pytorch=2.3.0
  - pytorch-cuda=12.1
  - pytorch-mutex=1.0
  - pyyaml=6.0.1
  - readline=8.2
  - setuptools=70.1.1
  - sympy=1.12.1
  - tk=8.6.13
  - torchtriton=2.3.0
  - typing_extensions=4.12.2
  - wheel=0.43.0
  - xz=5.2.6
  - yaml=0.2.5
  - pip:
      - accelerate==0.32.1
      - aiofiles==23.2.1
      - aiohttp==3.9.5
      - aiosignal==1.3.1
      - altair==5.3.0
      - annotated-types==0.7.0
      - anyio==4.4.0
      - async-timeout==4.0.3
      - attrs==23.2.0
      - certifi==2024.7.4
      - charset-normalizer==3.3.2
      - click==8.1.7
      - cloudpickle==3.0.0
      - cmake==3.30.0
      - coloredlogs==15.0.1
      - contourpy==1.2.1
      - cycler==0.12.1
      - datasets==2.20.0
      - dill==0.3.8
      - diskcache==5.6.3
      - distro==1.9.0
      - dnspython==2.6.1
      - email-validator==2.2.0
      - exceptiongroup==1.2.1
      - fastapi==0.111.0
      - fastapi-cli==0.0.4
      - ffmpy==0.3.2
      - fonttools==4.53.1
      - frozenlist==1.4.1
      - fsspec==2024.5.0
      - gekko==1.2.1
      - gradio==4.37.2
      - gradio-client==1.0.2
      - h11==0.14.0
      - httpcore==1.0.5
      - httptools==0.6.1
      - httpx==0.27.0
      - huggingface-hub==0.23.4
      - humanfriendly==10.0
      - idna==3.7
      - importlib-resources==6.4.0
      - interegular==0.3.3
      - jsonschema==4.22.0
      - jsonschema-specifications==2023.12.1
      - kiwisolver==1.4.5
      - lark==1.1.9
      - llvmlite==0.43.0
      - lm-format-enforcer==0.10.1
      - markdown-it-py==3.0.0
      - matplotlib==3.9.1
      - mdurl==0.1.2
      - msgpack==1.0.8
      - multidict==6.0.5
      - multiprocess==0.70.16
      - nest-asyncio==1.6.0
      - ninja==1.11.1.1
      - numba==0.60.0
      - numpy==1.26.4
      - nvidia-ml-py==12.555.43
      - nvidia-nccl-cu12==2.20.5
      - ollama==0.2.1
      - openai==1.35.10
      - optimum==1.21.2
      - orjson==3.10.6
      - outlines==0.0.46
      - packaging==24.1
      - pandas==2.2.2
      - peft==0.11.1
      - pillow==10.4.0
      - prometheus-client==0.20.0
      - prometheus-fastapi-instrumentator==7.0.0
      - protobuf==5.27.2
      - psutil==6.0.0
      - py-cpuinfo==9.0.0
      - pyairports==2.1.1
      - pyarrow==16.1.0
      - pyarrow-hotfix==0.6
      - pycountry==24.6.1
      - pydantic==2.8.2
      - pydantic-core==2.20.1
      - pydub==0.25.1
      - pygments==2.18.0
      - pyparsing==3.1.2
      - python-dateutil==2.9.0.post0
      - python-dotenv==1.0.1
      - python-multipart==0.0.9
      - pytz==2024.1
      - ray==2.31.0
      - referencing==0.35.1
      - regex==2024.5.15
      - requests==2.32.3
      - rich==13.7.1
      - rouge==1.0.1
      - rpds-py==0.18.1
      - ruff==0.5.1
      - safetensors==0.4.3
      - semantic-version==2.10.0
      - sentencepiece==0.2.0
      - shellingham==1.5.4
      - six==1.16.0
      - sniffio==1.3.1
      - starlette==0.37.2
      - tiktoken==0.7.0
      - tokenizers==0.19.1
      - tomlkit==0.12.0
      - toolz==0.12.1
      - torchvision==0.18.0
      - tqdm==4.66.4
      - transformers==4.42.3
      - typer==0.12.3
      - tzdata==2024.1
      - ujson==5.10.0
      - urllib3==2.2.2
      - uvicorn==0.30.1
      - uvloop==0.19.0
      - vllm==0.5.0
      - vllm-flash-attn==2.5.9
      - watchfiles==0.22.0
      - websockets==11.0.3
      - xformers==0.0.26.post1
      - xxhash==3.4.1
      - yarl==1.9.4
